### ISSUE TITLE
ansible script should generate infra docker network

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#16]
for the case when no mcloud server components deployed we can't start device containers because infra docker network not exists.
let' generate it forcibly dueing ansible preparation.

**Comment by vdelendik** [comment]
fixed. just do regular basic acceptance to close the ticket

**Comment by dhreben** [comment]
Fixed .
<img width="782" alt="Screenshot 2021-04-27 at 18 40 33" src="https://user-images.githubusercontent.com/50950954/116270771-0ec34080-a788-11eb-9a4a-d1c4f35124ec.png">
