### ISSUE TITLE
improve recreate device container parametrization

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#21]
device2docker recreate <param>
adjust code to read and parse correctly full device docker container name.

For now we have to run:
`device2docker recreate UDID-Name`
but wanna to support
`device2docker recreate device-UDID-Name`

**Comment by vdelendik** [comment]
fixed. after deployment using zebrunner from branch develop you could recreate docker using both syntax as described above

**Comment by dhreben** [comment]
Verified.
