### ISSUE TITLE
Device containers don't launch with the same identical images.      

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-android#25]
**Test scenario:**

1.git clone --recurse-submodule --https://github.com/zebrunner/mcloud-android.git
2.configure main.yml  from      `nano/roles/devices/vars/main.yml`
3.Run ansible script
4.docker images -a
5.docker ps -a
  
**Actual result :** Device containers don't launch with the same identical images

<img width="1297" alt="Screenshot 2021-04-27 at 01 15 20" src="https://user-images.githubusercontent.com/50950954/116157829-4d101f80-a6f6-11eb-9823-f177554e5e16.png">

<img width="1323" alt="Screenshot 2021-04-27 at 01 11 19" src="https://user-images.githubusercontent.com/50950954/116157917-74ff8300-a6f6-11eb-8295-7f5e5274e878.png">

**Comment by vdelendik** [comment]
fixed, during the testing generate several simple tags for android-device container and try to run with any.
exact version should be used starting from now

**Comment by dhreben** [comment]
Verified.
