### ISSUE TITLE
rename device2docker script to zebrunner-farm and integrate most common actions

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-android#26]
zebrunner-farm.sh script which should be able continue to support existing operations:
1. add device
2. remove device
3. recreate device
and provide new options:
4. start-all
5. stop-all
6. verify device (?)
7. verify-all (?)

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-android/pull/42
such options were implemented for renamed device2docker -> zebrunner-farm shell script:
```
      Usage: zebrunner-farm [option]
      Arguments:
          start   [udid] Start devices containers or exact device by udid
          stop    [udid] Stop and keep devices containers or exact device by udid
          restart [udid] Restart all devices containers or exact device by udid
          down    [udid] Stop and remove devices containers
          shutdown       Stop and remove devices container, destroy all configuration
          backup         Backup MCloud setup
          restore        Restore MCloud setup
          version        Version of MCloud device image
```

during the testing pay attention to the physical device connect/disconnect as this part of functionality wasn't tested at all.
as for the rest, please test each function - they should work as expected :)

**Comment by dhreben** [comment]
Verified.
Opened separate tickets https://github.com/zebrunner/mcloud-android/issues/58 , https://github.com/zebrunner/mcloud-android/issues/61 , https://github.com/zebrunner/mcloud-android/issues/62
