### ISSUE TITLE
name provider/location using meaningful value

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#27]
related ticket: https://github.com/zebrunner/mcloud/issues/94
for mcloud-android default name should be "mcloud-android". 
Let's add new parameter into main.yml. And inside readme we should recommend to specify actual physical short city name like NYC

**Comment by vdelendik** [comment]
Fixed. during setup let's update in `roles/devices/vars/main.yml` stf_provider_name to something different like NYC.
After setup for every device connected to this server "NYC" should be registered as Location

**Comment by dhreben** [comment]
Verified.
