### ISSUE TITLE
adjust setup process to use only appium.tar.gz

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#31]
https://github.com/zebrunner/mcloud-appium/issues/64
due to the above changes we have to simplify ansible script as appium already delivered with opencv4nodejs on board

**Comment by vdelendik** [comment]
fixed. to test please setup new android slave using mcloud-android; branch: develop
1. run all device containers
2. connect to any running container and check that opencv4node is available
```
//switch to node 10
npm link --force node@10
node
require('opencv4nodejs');
```
-> no error messages about not found module
```

**Comment by dhreben** [comment]
Verified.

Test scenario:

1.git clone --recurse-submodule --branch develop https://github.com/zebrunner/mcloud-android.git
2.update main_yml
3.ansible-playbook -vvv -i hosts --user=name --extra-vars "ansible_sudo_pass=pswrd" devices.yml
5.docker exec -ti <deviceContainerName> bash
6.npm link --force node@10
7.cd /opt/mcloud/appium/
8.node
9.require('opencv4nodejs');
10.Check that no error messages about not found module
