### ISSUE TITLE
investigate if we still need python3-pip for ansible script

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#40]
it seems like operations we did b ypython not exists anymore so we can try to remove it completely and test

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-android/commit/ad899455c99f614a198853b0e1da8edcb532520f
As it was the only component required sudo permissions to test we have to execute default `ansible-playbook -vvv -i hosts devices.yml` command and be able to setup mcloud android slave with all devices.

**Comment by dhreben** [comment]
Verified.
(base) build@mcloud:~/tools/dhreben/mcloud-android$ python3 --version 
Python 3.7.6
