### ISSUE TITLE
restore `registerDevices` devices tag for quicker ansible devices registration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#41]
let's return tag and comment in readme about possibility to reregister new devices faster without ssl etc roles execution

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-android/commit/4fe6a7e82ee7c5a4246c1b3c74a2874f250aae98#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23

during the testing scenario should be:
1. configure mcloud-android as is (keep 1-2 devices in reserve without adding them into the devices main.yml)
2. start everything to ensure that all registered devices are available
3. update `roles/devices/vars/main.yml` registering new device(s) from reserve
4. run `ansible-playbook -vvv -i hosts devices.yml --tag registerDevices` command
-> carefully review whole ansible console log. it should contain info only about devices rules! I.e. no information about nginx, ssl available there!
5. start/restart services (let @vdelendik know if devices are started automatically or not)
-> new devices appeare and might be used in stf

**Comment by dhreben** [comment]
Verified.
