### ISSUE TITLE
refactor udev rules for iOS/Android devices

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#53]
1. we have to setup udev rule to start usbmuxd service if iOS device is connected to Linux
https://github.com/shamanec/ios-appium-docker/blob/a55f4881b15c8e232b1d77835ed21655c56ed708/services.sh#L131

2. integrate iOS devices into the same udev rules as android or in separate file as implemented by @shamanec
https://github.com/shamanec/ios-appium-docker/blob/a55f4881b15c8e232b1d77835ed21655c56ed708/services.sh#L105

so after running ansible script all whitelisted devices should be registered in udev rules to remove/create containers asap after reconnections. So far for disconnected device our iOS containers constantly restarting...

**Comment by vdelendik** [comment]
completely redesigned udev rules handler making it much simpler and combining both IOS and Android logic.
We do actions (add/remove) only for affected device(s) instead of for loops as in 1.x generation.

During the testing:
1. reconnect physically every device one-by-one. On disconnect 2 containers including appium should be removed, on connect - created again
2. do mass reconnect (hub use-case). All connected to hub device/containers should be removed and started on hub on
3. do server reboot via cmd: `sudo reboot now`
4. do force reboot via power
Note: still unclear if containers might be removed for #3 and #4 but we suspect to have everything up&running after restart (to reconnect iOS automatically this one shoud be fixed: https://github.com/zebrunner/stf/issues/280 otherwise you have to click trust on every iOS manually)

**Comment by dhreben** [comment]
Verified.
Created separate ticket https://github.com/zebrunner/mcloud-android/issues/60
