### ISSUE TITLE
rename 51-android.rules udev rules file to something mcloud related

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#54]
as we have both Android and iOS supported by udev we have to rename template file.
note: think about upgrade process, as minimal add manual steps to remove old 51-android.rules

**Comment by vdelendik** [comment]
Done. 51-android.rules renamed to 90_mcloud.rules.
After setup and ansible script execution verify that `/etc/udev/rules.d/90_mcloud.rules` file generated with all whitelisted devices inside (android and ios).
Also test that during connect -> device containers created, on disconnect - removed.

**Comment by dhreben** [comment]
Verified.
