### ISSUE TITLE
investigate if we need NGIX share and ssl setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#55]
in scope of 2.0 we reorganized http/https and ws/wss detection using `PUBLIC_IP_PROTOCOL` env var.
it seems like we can remove NGINX related share and ssl.crt/ssl.key as arguments at all. websockify also removed from the stf provider docker image wehre we used such artifacts

**Comment by vdelendik** [comment]
Done. During the testing obligatory configure secured community-edition over https and connect mcloud-agent (former mcloud-android).
Devices displays should be accessible and visible using wss (it might be broken and if true - submit a new bug)

**Comment by dhreben** [comment]
Verified.
