### ISSUE TITLE
unable to manage devices manually using zebrunner-farm

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#57]
after improving udev integration we lost capabilitites to manage devices via shell script directly:
```
(base) build@mcloud:~/tools/vd/mcloud-android$ zebrunner-farm restart <udid>
ACTION: restart
do nothing as device id/udid missed.
```

we have to adjust logic to combine both manual and udev usage

**Comment by vdelendik** [comment]
fixed. to test we have to setup MCloud agent and be able to start/stop/restart/down device containers manually and automatically via udev rules

**Comment by dhreben** [comment]
Fixed.
