### ISSUE TITLE
Error:bash: /usr/local/bin/zebrunner-farm: No such file or directory after run zebrunner-farm shutdown

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-android#58]
**Steps:**

1. Run zebrunner-farm shutdown

**Actual result :** Error:bash: /usr/local/bin/zebrunner-farm: No such file or directory

Note: All docker containers are present

**Comment by vdelendik** [comment]
fixed. `shutdown` moved from zebrunner-farm into zebrunner.sh!
double check that in additions to removal of:
* /usr/local/bin/zebrunner-farm
* /usr/local/bin/devices.txt
* /etc/udev/rules.d/90_mcloud.rules
we also remove:
* roles/devices/vars/main.yml

**Comment by dhreben** [comment]
Fixed.
