### ISSUE TITLE
The Appium container don't start after it has been stopped

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-android#61]
**Steps:**

**Case 1:**

1.zebrunner-farm stop [udid]
2.zebrunner-farm start [udid]

**Actual result:** The Appium containers don't start after it has been stopped

Note: The same case without [udid]

**Comment by vdelendik** [comment]
fixed. start operation was commented somehow.

**Comment by dhreben** [comment]
Fixed.
