### ISSUE TITLE
 The main.yml file is absent in the backup folder after run zebrunner-farm backup

### ISSUE THREAD

**Issue by dhreben** [zebrunner/mcloud-android#62]
**Steps**:

1. Run Zebrunner-farm backup
2. cd backup folder

**Actual result:**  The main.yml file is absent in the backup folder after run zebrunner-farm backup

**Comment by vdelendik** [comment]
fixed. backup/restore moved to the zebrunner.sh and removed from zebrunner-farm. Also in scope of shutdown/setup improvements main.yml.original is the only located in git

**Comment by dhreben** [comment]
Fixed
