### ISSUE TITLE
default-capabilities is missed for iOS appium

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#69]
we do generate defaultcapabilities.json for iOS as minimal which include default data for appium per device, for example:
```
{
  "udid":"$DEVICE_UDID",
  "mjpegServerPort": ${MJPEG_PORT},
  "clearSystemFiles": "false",
  "webDriverAgentUrl":"http://${WDA_HOST}:${WDA_PORT}",
  "preventWDAAttachments": "true",
  "simpleIsVisibleCheck": "true",
  "wdaLocalPort": "${WDA_PORT}",
  "platformVersion": "${PLATFORM_VERSION}",
  "automationName":"${AUTOMATION_NAME}",
  "platformName": "${PLATFORM_NAME}",
  "deviceName": "${DEVICE_NAME}"
}
```

We have to provide `DEFAULT_CAPABILITIES=true` to be able to init these values. Also think about similar approach for Android as well.

Without default capabilities it is impossible to run iOS without explicitly adding: udid, webDriverAgent, automationName, and platformVersion

**Comment by vdelendik** [comment]
fixed adding `DEFAULT_CAPABILITIES=true` for both iOS and Android appium containers.
To test just bash into the android and iOS appium container and run `export` command.
Among env vars you should see `DEFAULT_CAPABILITIES=true`

**Comment by dhreben** [comment]
Fixed
