### ISSUE TITLE
remove STF_HOST_PROVIDER_PUBLIC for Android

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/mcloud-android#9]
https://github.com/zebrunner/mcloud/issues/76

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/mcloud-android/commit/9e64b0e82cce53dfa132adaade7a165b6a109169

**Comment by vdelendik** [comment]
readme should be updated as well!

**Comment by vdelendik** [comment]
updated mcloud-android readme as well

**Comment by dhreben** [comment]
Verified.
